/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singletonusuario;

import java.util.ArrayList;

/**
 *
 * @author drone
 */
public class PanelUsuario extends javax.swing.JFrame {

    protected static int numinvitados = 0;
    protected static int NUMERO_INVITADOS = 0;
    protected static PanelUsuario panel;

    int letra = 'a';
    int cont =0;
    private PanelUsuario() {
        initComponents();
    }
    
    public char mostrarLetra(){
        return (char)(letra + cont);
    }

    
    public static PanelUsuario getInstance(String usuario, String pass){
        System.err.println(numinvitados + " " +NUMERO_INVITADOS  );
        if(panel == null){
            if(numinvitados < NUMERO_INVITADOS && busquedaUsuario(usuario, pass)){
                
                numinvitados++;
                panel = new PanelUsuario();
            }
            return null;
        } 
        else{
            return null;
        }
    }
    
    
    public static boolean busquedaUsuario(String usuario, String pass){
        ArrayList<String> passl = Credenciales.getPassword();
        ArrayList<String> userl = Credenciales.getUsuario();
        ArrayList<String> tipol = Credenciales.getTipo();
        
        int pos = -1;
        for(int i=0; i<userl.size(); i++){
            if(userl.get(i).equals(usuario)){
                pos = i;
                break;
            }
        }
        
        if(passl.get(pos).equals(pass)){
            return true;
        }
        return false;
    }
    public void cerrarSession(){
        panel = null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrarLetra = new javax.swing.JButton();
        textLetras = new javax.swing.JTextField();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mostrarLetra.setText("Mostra");
        mostrarLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarLetraActionPerformed(evt);
            }
        });

        cerrar.setText("Cerrar Sesion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(mostrarLetra)
                .addGap(38, 38, 38)
                .addComponent(textLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostrarLetra)
                    .addComponent(textLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(cerrar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarLetraActionPerformed
        textLetras.setText(textLetras.getText() + " " + mostrarLetra());
        cont++;
    }//GEN-LAST:event_mostrarLetraActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrar;
    private javax.swing.JButton mostrarLetra;
    private javax.swing.JTextField textLetras;
    // End of variables declaration//GEN-END:variables
}
